/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DonationPlatformContract } from "./DonationPlatformContract";
export * as factories from "./factories";
export { DonationPlatformContract__factory } from "./factories/DonationPlatformContract__factory";
